### ISSUE TITLE
the text to prompt doesn't work?

### ISSUE THREAD

**Issue by angelOnly** [toshiaki1729/stable-diffusion-webui-text2prompt#4]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/18018532/226529948-5d2d333d-3f71-49e4-8a62-ac132436c6c8.png">
The above image shows the test result, which did not provide the prompt as instructed.

**Comment by angelOnly** [comment]
Sorry, after waiting a few minutes, the sentence result was displayed in the output box without any issue.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/18018532/226530373-a48c3ffb-610d-4b93-8352-1aa3d0256bef.png">

**Comment by toshiaki1729** [comment]
This extension takes few minutes at the first time to download language model.
Thank you.
